import { normalizeIdentifier, normalizeRelationships, primaryKeyColumns, type Schema, type Table, type Column, type KeyStrategy, type ForeignKeyRef, typeString } from "./schema";

function shorten(value: string, used: Set<string>) {
  const clean = normalizeIdentifier(value);
  if (clean.length <= 128 && !used.has(clean)) { used.add(clean); return clean; }
  const hash = [...clean].reduce((acc, char) => (acc * 31 + char.charCodeAt(0)) % 46656, 7).toString(36).toUpperCase().padStart(3, "0");
  const candidate = `${clean.slice(0, 124 - hash.length)}_${hash}`;
  used.add(candidate);
  return candidate;
}

function generatedName(prefix: string, table: Table, column?: Column, used = new Set<string>()) {
  return shorten([prefix, normalizeIdentifier(table.name), column && normalizeIdentifier(column.name)].filter(Boolean).join("_"), used);
}

function sqlComment(value: string) {
  return value.replaceAll("'", "''");
}

function keyStrategyArtifacts(table: Table, strategy: KeyStrategy, used: Set<string>) {
  const pk = primaryKeyColumns(table);
  if (strategy === "none" || pk.length !== 1 || pk[0].type !== "NUMBER") return [];
  const tableName = normalizeIdentifier(table.name);
  const sequenceName = generatedName("SEQ", table, undefined, used);
  const triggerName = generatedName("TRG", table, undefined, used);
  if (strategy === "identity") return [];
  return [
    `CREATE SEQUENCE ${sequenceName} START WITH 1 INCREMENT BY 1 NOCACHE;`,
    `\nCREATE OR REPLACE TRIGGER ${triggerName}`,
    `BEFORE INSERT ON ${tableName}`,
    `FOR EACH ROW`,
    `BEGIN`,
    `  IF :NEW.${normalizeIdentifier(pk[0].name)} IS NULL THEN`,
    `    :NEW.${normalizeIdentifier(pk[0].name)} := ${sequenceName}.NEXTVAL;`,
    `  END IF;`,
    `END;`,
    `/`,
  ];
}

export function generateDDL(schema: Schema) {
  const out = ["-- ============================================================", "-- Oracle DDL generated by Oracle Schema Designer", "-- Target: Oracle 12.2+", "-- ============================================================\n"];
  const usedNames = new Set<string>();
  schema.tables.forEach((table) => {
    const tableName = normalizeIdentifier(table.name);
    const pk = primaryKeyColumns(table);
    const strategy = table.keyStrategy;
    out.push(`--drop table ${tableName};`, "--", `create table ${tableName} (`);
    const lines = table.columns.map((column) => {
      const attrs = [column.notNull || column.pk ? "not null" : "", column.defaultValue.trim() ? `default ${column.defaultValue.trim()}` : ""].filter(Boolean).join(" ");
      const identity = strategy === "identity" && column.pk && pk.length === 1 && column.type === "NUMBER" ? " GENERATED ALWAYS AS IDENTITY" : "";
      return `  ${normalizeIdentifier(column.name)} ${typeString(column)}${identity}${attrs ? ` ${attrs}` : ""}`;
    });
    out.push(lines.join(",\n"), ") tablespace CORE_DATA;", "--", "");
  });

  schema.tables.forEach((table) => {
    const tableName = normalizeIdentifier(table.name);
    const pk = primaryKeyColumns(table);
    if (pk.length) out.push(`alter table ${tableName}`, `  add constraint ${generatedName("PK", table, undefined, usedNames)} primary key (${pk.map((column) => normalizeIdentifier(column.name)).join(", ")})`, "  using index tablespace CORE_INDEX;", "--");
    table.columns.filter((column) => column.unique).forEach((column) => out.push(`alter table ${tableName}`, `  add constraint ${generatedName("U", table, column, usedNames)} unique (${normalizeIdentifier(column.name)})`, "  using index tablespace CORE_INDEX;", "--"));
    table.columns.filter((column) => column.check.trim()).forEach((column) => out.push(`alter table ${tableName}`, `  add constraint ${generatedName("C", table, column, usedNames)}`, `  check (${column.check.trim()});`, "--"));
    if (table.comment?.trim()) out.push(`comment on table ${tableName} is '${sqlComment(table.comment.trim())}';`, "--");
    table.columns.filter((column) => column.comment?.trim()).forEach((column) => out.push(`comment on column ${tableName}.${normalizeIdentifier(column.name)} is '${sqlComment(column.comment!.trim())}';`, "--"));
  });

  schema.tables.forEach((table) => out.push(...keyStrategyArtifacts(table, table.keyStrategy, usedNames), "--"));

  const fks: string[] = [];
  const canonical = normalizeRelationships({ ...schema, relationships: schema.relationships?.length ? schema.relationships : undefined });
  canonical.relationships?.forEach((relationship) => {
    const startTable = canonical.tables.find((table) => table.id === relationship.startTableId);
    const endTable = canonical.tables.find((table) => table.id === relationship.endTableId);
    if (!startTable || !endTable) return;
    const pairs = relationship.fields.length ? relationship.fields : [{ startFieldId: relationship.startFieldId, endFieldId: relationship.endFieldId }];
    const startColumns = pairs.map((pair) => startTable.columns.find((column) => column.id === pair.startFieldId)).filter((column): column is Column => Boolean(column));
    const endColumns = pairs.map((pair) => endTable.columns.find((column) => column.id === pair.endFieldId)).filter((column): column is Column => Boolean(column));
    if (startColumns.length !== pairs.length || endColumns.length !== pairs.length) return;
    const constraintName = generatedName("F", startTable, startColumns[0], usedNames);
    const deleteAction = relationship.deleteConstraint === "Cascade" || relationship.deleteConstraint === "Set null"
      ? ` on delete ${relationship.deleteConstraint.toLowerCase()}`
      : "";
    const unsupportedActions = [
      relationship.updateConstraint !== "No action" ? `-- DrawDB ON UPDATE: ${relationship.updateConstraint}` : "",
      relationship.deleteConstraint !== "No action" && !deleteAction ? `-- DrawDB ON DELETE: ${relationship.deleteConstraint}` : "",
    ].filter(Boolean);
    fks.push(
      ...unsupportedActions,
      `alter table ${normalizeIdentifier(startTable.name)}`,
      `  add constraint ${shorten(relationship.name || constraintName, usedNames)}`,
      `  foreign key (${startColumns.map((column) => normalizeIdentifier(column.name)).join(", ")}) references ${normalizeIdentifier(endTable.name)}(${endColumns.map((column) => normalizeIdentifier(column.name)).join(", ")})${deleteAction};`,
      "--",
    );
  });
  if (fks.length) out.push(...fks, "");
  return out.join("\n");
}

function param(column: Column, tableName: string, mode = "IN") {
  return `p_${normalizeIdentifier(column.name).toLowerCase()} ${mode} ${tableName}.${normalizeIdentifier(column.name)}%TYPE`;
}

export function generatePLSQL(schema: Schema) {
  const out = ["-- ============================================================", "-- PL/SQL CRUD packages generated by Oracle Schema Designer", "-- ============================================================\n"];
  schema.tables.forEach((table) => {
    const tableName = normalizeIdentifier(table.name);
    const pkg = `PKG_${tableName}`;
    const pk = primaryKeyColumns(table);
    out.push(`CREATE OR REPLACE PACKAGE ${pkg} AS`);
    if (pk.length === 1) {
      const pkColumn = pk[0];
      const nonPk = table.columns.filter((column) => !column.pk);
      out.push(`  PROCEDURE P_INSERT(${nonPk.map((column) => param(column, tableName)).concat(param(pkColumn, tableName, "OUT")).join(", ")});`);
      out.push(`  PROCEDURE P_UPDATE(${[param(pkColumn, tableName), ...nonPk.map((column) => param(column, tableName))].join(", ")});`);
      out.push(`  PROCEDURE P_DELETE(${param(pkColumn, tableName)});`);
      out.push(`  FUNCTION F_GET(${param(pkColumn, tableName)}) RETURN SYS_REFCURSOR;`);
      out.push(`  FUNCTION F_LIST(p_limit IN PLS_INTEGER DEFAULT 50, p_offset IN PLS_INTEGER DEFAULT 0) RETURN SYS_REFCURSOR;`);
    } else out.push(`  -- ${pk.length ? "composite" : "no"} primary key: CRUD requires a key-specific procedure design`);
    out.push(`END ${pkg};`, "/", "", `CREATE OR REPLACE PACKAGE BODY ${pkg} AS`);
    if (pk.length === 1) {
      const key = pk[0];
      const nonPk = table.columns.filter((column) => !column.pk);
      const keyParam = `p_${normalizeIdentifier(key.name).toLowerCase()}`;
      out.push(`  PROCEDURE P_INSERT(${nonPk.map((column) => param(column, tableName)).concat(param(key, tableName, "OUT")).join(", ")}) IS`, "  BEGIN", `    INSERT INTO ${tableName} (${nonPk.map((column) => normalizeIdentifier(column.name)).join(", ")})`, `    VALUES (${nonPk.map((column) => `p_${normalizeIdentifier(column.name).toLowerCase()}`).join(", ")})`, `    RETURNING ${normalizeIdentifier(key.name)} INTO ${keyParam};`, "  END P_INSERT;", "");
      out.push(`  PROCEDURE P_UPDATE(${[param(key, tableName), ...nonPk.map((column) => param(column, tableName))].join(", ")}) IS`, "  BEGIN", `    UPDATE ${tableName} SET`, nonPk.map((column, index) => `      ${normalizeIdentifier(column.name)} = p_${normalizeIdentifier(column.name).toLowerCase()}${index === nonPk.length - 1 ? "" : ","}`).join("\n"), `    WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`, "  END P_UPDATE;", "");
      out.push(`  PROCEDURE P_DELETE(${param(key, tableName)}) IS`, "  BEGIN", `    DELETE FROM ${tableName} WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`, "  END P_DELETE;", "");
      out.push(`  FUNCTION F_GET(${param(key, tableName)}) RETURN SYS_REFCURSOR IS`, "    v_cur SYS_REFCURSOR;", "  BEGIN", `    OPEN v_cur FOR SELECT * FROM ${tableName} WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`, "    RETURN v_cur;", "  END F_GET;", "");
      out.push(`  FUNCTION F_LIST(p_limit IN PLS_INTEGER DEFAULT 50, p_offset IN PLS_INTEGER DEFAULT 0) RETURN SYS_REFCURSOR IS`, "    v_cur SYS_REFCURSOR;", "  BEGIN", `    OPEN v_cur FOR SELECT * FROM ${tableName} OFFSET p_offset ROWS FETCH NEXT p_limit ROWS ONLY;`, "    RETURN v_cur;", "  END F_LIST;");
    }
    out.push(`END ${pkg};`, "/", "");
  });
  return out.join("\n");
}

export function exportSchema(schema: Schema) {
  return `${generateDDL(schema)}\n\n${generatePLSQL(schema)}`;
}
