import { normalizeIdentifier, primaryKeyColumns, type Schema, type Table, type Column, type KeyStrategy, type ForeignKeyRef, typeString } from "./schema";

function shorten(value: string, used: Set<string>) {
  const clean = normalizeIdentifier(value);
  if (clean.length <= 128 && !used.has(clean)) { used.add(clean); return clean; }
  const hash = [...clean].reduce((acc, char) => (acc * 31 + char.charCodeAt(0)) % 46656, 7).toString(36).toUpperCase().padStart(3, "0");
  const candidate = `${clean.slice(0, 124 - hash.length)}_${hash}`;
  used.add(candidate);
  return candidate;
}

function generatedName(prefix: string, table: Table, column?: Column, used = new Set<string>()) {
  return shorten([prefix, normalizeIdentifier(table.name), column && normalizeIdentifier(column.name)].filter(Boolean).join("_"), used);
}

function keyStrategyArtifacts(table: Table, strategy: KeyStrategy, used: Set<string>) {
  const pk = primaryKeyColumns(table);
  if (strategy === "none" || pk.length !== 1 || pk[0].type !== "NUMBER") return [];
  const tableName = normalizeIdentifier(table.name);
  const sequenceName = generatedName("SEQ", table, undefined, used);
  const triggerName = generatedName("TRG", table, undefined, used);
  if (strategy === "identity") return [];
  return [
    `CREATE SEQUENCE ${sequenceName} START WITH 1 INCREMENT BY 1 NOCACHE;`,
    `\nCREATE OR REPLACE TRIGGER ${triggerName}`,
    `BEFORE INSERT ON ${tableName}`,
    `FOR EACH ROW`,
    `BEGIN`,
    `  IF :NEW.${normalizeIdentifier(pk[0].name)} IS NULL THEN`,
    `    :NEW.${normalizeIdentifier(pk[0].name)} := ${sequenceName}.NEXTVAL;`,
    `  END IF;`,
    `END;`,
    `/`,
  ];
}

export function generateDDL(schema: Schema) {
  const out = ["-- ============================================================", "-- Oracle DDL generated by Oracle Schema Designer", "-- Target: Oracle 12.2+", "-- ============================================================\n"];
  const usedNames = new Set<string>();
  schema.tables.forEach((table) => {
    const tableName = normalizeIdentifier(table.name);
    const pk = primaryKeyColumns(table);
    const strategy = table.keyStrategy;
    out.push(...keyStrategyArtifacts(table, strategy, usedNames));
    out.push(`\nCREATE TABLE ${tableName} (`);
    const lines = table.columns.map((column) => {
      const attrs = [column.notNull || column.pk ? "NOT NULL" : "", column.unique ? "UNIQUE" : "", column.defaultValue.trim() ? `DEFAULT ${column.defaultValue.trim()}` : ""].filter(Boolean).join(" ");
      const identity = strategy === "identity" && column.pk && pk.length === 1 && column.type === "NUMBER" ? " GENERATED ALWAYS AS IDENTITY" : "";
      return `  ${normalizeIdentifier(column.name)} ${typeString(column)}${identity}${attrs ? ` ${attrs}` : ""}`;
    });
    if (pk.length) lines.push(`  CONSTRAINT ${generatedName("PK", table, undefined, usedNames)} PRIMARY KEY (${pk.map((column) => normalizeIdentifier(column.name)).join(", ")})`);
    table.columns.filter((column) => column.check.trim()).forEach((column) => lines.push(`  CONSTRAINT ${generatedName("CK", table, column, usedNames)} CHECK (${column.check.trim()})`));
    out.push(lines.join(",\n"), ");", "");
  });
  const fks: string[] = [];
  schema.tables.forEach((table) => table.columns.forEach((column) => {
    if (!column.fk) return;
    const target = schema.tables.find((candidate) => candidate.id === column.fk?.tableId);
    const targetColumn = target?.columns.find((candidate) => candidate.id === column.fk?.columnId);
    if (!target || !targetColumn || primaryKeyColumns(target).length > 1) return;
    fks.push(`ALTER TABLE ${normalizeIdentifier(table.name)} ADD CONSTRAINT ${generatedName("FK", table, column, usedNames)} FOREIGN KEY (${normalizeIdentifier(column.name)}) REFERENCES ${normalizeIdentifier(target.name)}(${normalizeIdentifier(targetColumn.name)});`);
  }));
  if (fks.length) out.push("-- Foreign key constraints", ...fks, "");
  return out.join("\n");
}

function param(column: Column, tableName: string, mode = "IN") {
  return `p_${normalizeIdentifier(column.name).toLowerCase()} ${mode} ${tableName}.${normalizeIdentifier(column.name)}%TYPE`;
}

export function generatePLSQL(schema: Schema) {
  const out = ["-- ============================================================", "-- PL/SQL CRUD packages generated by Oracle Schema Designer", "-- ============================================================\n"];
  schema.tables.forEach((table) => {
    const tableName = normalizeIdentifier(table.name);
    const pkg = `PKG_${tableName}`;
    const pk = primaryKeyColumns(table);
    out.push(`CREATE OR REPLACE PACKAGE ${pkg} AS`);
    if (pk.length === 1) {
      const pkColumn = pk[0];
      const nonPk = table.columns.filter((column) => !column.pk);
      out.push(`  PROCEDURE P_INSERT(${nonPk.map((column) => param(column, tableName)).concat(param(pkColumn, tableName, "OUT")).join(", ")});`);
      out.push(`  PROCEDURE P_UPDATE(${[param(pkColumn, tableName), ...nonPk.map((column) => param(column, tableName))].join(", ")});`);
      out.push(`  PROCEDURE P_DELETE(${param(pkColumn, tableName)});`);
      out.push(`  FUNCTION F_GET(${param(pkColumn, tableName)}) RETURN SYS_REFCURSOR;`);
      out.push(`  FUNCTION F_LIST(p_limit IN PLS_INTEGER DEFAULT 50, p_offset IN PLS_INTEGER DEFAULT 0) RETURN SYS_REFCURSOR;`);
    } else out.push(`  -- ${pk.length ? "composite" : "no"} primary key: CRUD requires a key-specific procedure design`);
    out.push(`END ${pkg};`, "/", "", `CREATE OR REPLACE PACKAGE BODY ${pkg} AS`);
    if (pk.length === 1) {
      const key = pk[0];
      const nonPk = table.columns.filter((column) => !column.pk);
      const keyParam = `p_${normalizeIdentifier(key.name).toLowerCase()}`;
      out.push(`  PROCEDURE P_INSERT(${nonPk.map((column) => param(column, tableName)).concat(param(key, tableName, "OUT")).join(", ")}) IS`, "  BEGIN", `    INSERT INTO ${tableName} (${nonPk.map((column) => normalizeIdentifier(column.name)).join(", ")})`, `    VALUES (${nonPk.map((column) => `p_${normalizeIdentifier(column.name).toLowerCase()}`).join(", ")})`, `    RETURNING ${normalizeIdentifier(key.name)} INTO ${keyParam};`, "  END P_INSERT;", "");
      out.push(`  PROCEDURE P_UPDATE(${[param(key, tableName), ...nonPk.map((column) => param(column, tableName))].join(", ")}) IS`, "  BEGIN", `    UPDATE ${tableName} SET`, nonPk.map((column, index) => `      ${normalizeIdentifier(column.name)} = p_${normalizeIdentifier(column.name).toLowerCase()}${index === nonPk.length - 1 ? "" : ","}`).join("\n"), `    WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`, "  END P_UPDATE;", "");
      out.push(`  PROCEDURE P_DELETE(${param(key, tableName)}) IS`, "  BEGIN", `    DELETE FROM ${tableName} WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`, "  END P_DELETE;", "");
      out.push(`  FUNCTION F_GET(${param(key, tableName)}) RETURN SYS_REFCURSOR IS`, "    v_cur SYS_REFCURSOR;", "  BEGIN", `    OPEN v_cur FOR SELECT * FROM ${tableName} WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`, "    RETURN v_cur;", "  END F_GET;", "");
      out.push(`  FUNCTION F_LIST(p_limit IN PLS_INTEGER DEFAULT 50, p_offset IN PLS_INTEGER DEFAULT 0) RETURN SYS_REFCURSOR IS`, "    v_cur SYS_REFCURSOR;", "  BEGIN", `    OPEN v_cur FOR SELECT * FROM ${tableName} OFFSET p_offset ROWS FETCH NEXT p_limit ROWS ONLY;`, "    RETURN v_cur;", "  END F_LIST;");
    }
    out.push(`END ${pkg};`, "/", "");
  });
  return out.join("\n");
}

export function exportSchema(schema: Schema) {
  return `${generateDDL(schema)}\n\n${generatePLSQL(schema)}`;
}
