import {
  normalizeIdentifier,
  normalizeRelationships,
  primaryKeyColumns,
  type Schema,
  type Table,
  type Column,
  type KeyStrategy,
  type ForeignKeyRef,
  typeString,
} from "./schema";

function shorten(value: string, used: Set<string>) {
  const clean = normalizeIdentifier(value).toLowerCase();
  if (clean.length <= 128 && !used.has(clean)) {
    used.add(clean);
    return clean;
  }
  const hash = [...clean]
    .reduce((acc, char) => (acc * 31 + char.charCodeAt(0)) % 46656, 7)
    .toString(36)
    .toUpperCase()
    .padStart(3, "0");
  const candidate = `${clean.slice(0, 124 - hash.length)}_${hash}`;
  used.add(candidate);
  return candidate;
}

function sqlIdentifier(value: string) {
  return normalizeIdentifier(value).toLowerCase();
}

function sqlComment(value: string) {
  return value.replaceAll("'", "''");
}

function keyStrategyArtifacts(
  table: Table,
  strategy: KeyStrategy,
  used: Set<string>,
) {
  const pk = primaryKeyColumns(table);
  if (strategy === "none" || pk.length !== 1 || pk[0].type !== "NUMBER")
    return [];
  const tableName = sqlIdentifier(table.name);
  const sequenceName = shorten(`${tableName}_seq`, used);
  if (strategy === "identity") return [];
  return [
    `create sequence ${sequenceName}`,
    "start with 500",
    "increment by 1",
    "nocache",
    "nocycle;",
  ];
}

export function generateDDL(schema: Schema) {
  const out = [
    "-- ============================================================",
    "-- Oracle DDL generated by Oracle Schema Designer",
    "-- Target: Oracle 12.2+",
    "-- ============================================================\n",
  ];
  const usedNames = new Set<string>();
  const canonical = normalizeRelationships({
    ...schema,
    relationships: schema.relationships?.length
      ? schema.relationships
      : undefined,
  });
  const relationshipsByTable = new Map<
    string,
    typeof canonical.relationships
  >();
  canonical.relationships?.forEach((relationship) => {
    const current = relationshipsByTable.get(relationship.startTableId) ?? [];
    current.push(relationship);
    relationshipsByTable.set(relationship.startTableId, current);
  });

  canonical.tables.forEach((table) => {
    const tableName = sqlIdentifier(table.name);
    const pk = primaryKeyColumns(table);
    const outgoing = relationshipsByTable.get(table.id) ?? [];
    const strategy = table.keyStrategy;
    out.push(`--drop table ${tableName};`, "--", `create table ${tableName} (`);
    const columnNameWidth = Math.max(
      ...table.columns.map((column) => sqlIdentifier(column.name).length),
      0,
    );
    const lines = table.columns.map((column) => {
      const attrs = [
        column.defaultValue.trim()
          ? `default ${column.defaultValue.trim()}`
          : "",
        column.notNull || column.pk ? "not null" : "",
      ]
        .filter(Boolean)
        .join(" ");
      const identity =
        strategy === "identity" &&
        column.pk &&
        pk.length === 1 &&
        column.type === "NUMBER"
          ? " generated always as identity"
          : "";
      return `  ${sqlIdentifier(column.name).padEnd(columnNameWidth + 3)}${typeString(column).toLowerCase()}${identity}${attrs ? ` ${attrs}` : ""}`;
    });
    out.push(lines.join(",\n"), ") tablespace core_data;", "--");

    if (pk.length)
      out.push(
        `alter table ${tableName}`,
        `  add constraint ${shorten(`${tableName}_pk`, usedNames)} primary key (${pk.map((column) => sqlIdentifier(column.name)).join(", ")})`,
        "  using index tablespace core_index;",
        "--",
      );
    table.columns
      .filter((column) => column.unique)
      .forEach((column, index) =>
        out.push(
          `alter table ${tableName}`,
          `  add constraint ${shorten(`${tableName}_u${index + 1}`, usedNames)} unique (${sqlIdentifier(column.name)})`,
          "  using index tablespace core_index;",
          "--",
        ),
      );
    table.columns
      .filter((column) => column.check.trim())
      .forEach((column, index) =>
        out.push(
          `alter table ${tableName}`,
          `  add constraint ${shorten(`${tableName}_c${index + 1}`, usedNames)}`,
          `  check (${column.check.trim()});`,
          "--",
        ),
      );

    outgoing.forEach((relationship) => {
      const endTable = canonical.tables.find(
        (candidate) => candidate.id === relationship.endTableId,
      );
      if (!endTable) return;
      const pairs = relationship.fields.length
        ? relationship.fields
        : [
            {
              startFieldId: relationship.startFieldId,
              endFieldId: relationship.endFieldId,
            },
          ];
      const startColumns = pairs
        .map((pair) =>
          table.columns.find((column) => column.id === pair.startFieldId),
        )
        .filter((column): column is Column => Boolean(column));
      const endColumns = pairs
        .map((pair) =>
          endTable.columns.find((column) => column.id === pair.endFieldId),
        )
        .filter((column): column is Column => Boolean(column));
      if (
        startColumns.length !== pairs.length ||
        endColumns.length !== pairs.length
      )
        return;
      const deleteAction =
        relationship.deleteConstraint === "Cascade" ||
        relationship.deleteConstraint === "Set null"
          ? ` on delete ${relationship.deleteConstraint.toLowerCase()}`
          : "";
      if (relationship.updateConstraint !== "No action")
        out.push(`-- DrawDB on update: ${relationship.updateConstraint}`);
      if (relationship.deleteConstraint !== "No action" && !deleteAction)
        out.push(`-- DrawDB on delete: ${relationship.deleteConstraint}`);
      out.push(
        `alter table ${tableName}`,
        `  add constraint ${shorten(relationship.name || `${tableName}_f${outgoing.indexOf(relationship) + 1}`, usedNames)}`,
        `  foreign key (${startColumns.map((column) => sqlIdentifier(column.name)).join(", ")}) references ${sqlIdentifier(endTable.name)}(${endColumns.map((column) => sqlIdentifier(column.name)).join(", ")})${deleteAction};`,
        "--",
      );
    });

    if (table.comment?.trim())
      out.push(
        `comment on table ${tableName} is '${sqlComment(table.comment.trim())}';`,
      );
    table.columns
      .filter((column) => column.comment?.trim())
      .forEach((column) =>
        out.push(
          `comment on column ${tableName}.${sqlIdentifier(column.name)} is '${sqlComment(column.comment!.trim())}';`,
        ),
      );
    out.push("");
  });

  const sequenceTables = canonical.tables.filter(
    (table) =>
      keyStrategyArtifacts(table, table.keyStrategy, new Set()).length > 0,
  );

  sequenceTables.forEach((table, index) => {
    const artifacts = keyStrategyArtifacts(table, table.keyStrategy, usedNames);
    if (artifacts.length)
      out.push(
        ...artifacts,
        ...(index < sequenceTables.length - 1
          ? ["---------------------------------------------------------"]
          : []),
      );
  });
  return out.join("\n");
}

function param(column: Column, tableName: string, mode = "IN") {
  return `p_${normalizeIdentifier(column.name).toLowerCase()} ${mode} ${tableName}.${normalizeIdentifier(column.name)}%TYPE`;
}

export function generatePLSQL(schema: Schema) {
  const out = [
    "-- ============================================================",
    "-- PL/SQL CRUD packages generated by Oracle Schema Designer",
    "-- ============================================================\n",
  ];
  schema.tables.forEach((table) => {
    const tableName = normalizeIdentifier(table.name);
    const pkg = `PKG_${tableName}`;
    const pk = primaryKeyColumns(table);
    out.push(`CREATE OR REPLACE PACKAGE ${pkg} AS`);
    if (pk.length === 1) {
      const pkColumn = pk[0];
      const nonPk = table.columns.filter((column) => !column.pk);
      out.push(
        `  PROCEDURE P_INSERT(${nonPk
          .map((column) => param(column, tableName))
          .concat(param(pkColumn, tableName, "OUT"))
          .join(", ")});`,
      );
      out.push(
        `  PROCEDURE P_UPDATE(${[param(pkColumn, tableName), ...nonPk.map((column) => param(column, tableName))].join(", ")});`,
      );
      out.push(`  PROCEDURE P_DELETE(${param(pkColumn, tableName)});`);
      out.push(
        `  FUNCTION F_GET(${param(pkColumn, tableName)}) RETURN SYS_REFCURSOR;`,
      );
      out.push(
        `  FUNCTION F_LIST(p_limit IN PLS_INTEGER DEFAULT 50, p_offset IN PLS_INTEGER DEFAULT 0) RETURN SYS_REFCURSOR;`,
      );
    } else
      out.push(
        `  -- ${pk.length ? "composite" : "no"} primary key: CRUD requires a key-specific procedure design`,
      );
    out.push(
      `END ${pkg};`,
      "/",
      "",
      `CREATE OR REPLACE PACKAGE BODY ${pkg} AS`,
    );
    if (pk.length === 1) {
      const key = pk[0];
      const nonPk = table.columns.filter((column) => !column.pk);
      const keyParam = `p_${normalizeIdentifier(key.name).toLowerCase()}`;
      out.push(
        `  PROCEDURE P_INSERT(${nonPk
          .map((column) => param(column, tableName))
          .concat(param(key, tableName, "OUT"))
          .join(", ")}) IS`,
        "  BEGIN",
        `    INSERT INTO ${tableName} (${nonPk.map((column) => normalizeIdentifier(column.name)).join(", ")})`,
        `    VALUES (${nonPk.map((column) => `p_${normalizeIdentifier(column.name).toLowerCase()}`).join(", ")})`,
        `    RETURNING ${normalizeIdentifier(key.name)} INTO ${keyParam};`,
        "  END P_INSERT;",
        "",
      );
      out.push(
        `  PROCEDURE P_UPDATE(${[param(key, tableName), ...nonPk.map((column) => param(column, tableName))].join(", ")}) IS`,
        "  BEGIN",
        `    UPDATE ${tableName} SET`,
        nonPk
          .map(
            (column, index) =>
              `      ${normalizeIdentifier(column.name)} = p_${normalizeIdentifier(column.name).toLowerCase()}${index === nonPk.length - 1 ? "" : ","}`,
          )
          .join("\n"),
        `    WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`,
        "  END P_UPDATE;",
        "",
      );
      out.push(
        `  PROCEDURE P_DELETE(${param(key, tableName)}) IS`,
        "  BEGIN",
        `    DELETE FROM ${tableName} WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`,
        "  END P_DELETE;",
        "",
      );
      out.push(
        `  FUNCTION F_GET(${param(key, tableName)}) RETURN SYS_REFCURSOR IS`,
        "    v_cur SYS_REFCURSOR;",
        "  BEGIN",
        `    OPEN v_cur FOR SELECT * FROM ${tableName} WHERE ${normalizeIdentifier(key.name)} = ${keyParam};`,
        "    RETURN v_cur;",
        "  END F_GET;",
        "",
      );
      out.push(
        `  FUNCTION F_LIST(p_limit IN PLS_INTEGER DEFAULT 50, p_offset IN PLS_INTEGER DEFAULT 0) RETURN SYS_REFCURSOR IS`,
        "    v_cur SYS_REFCURSOR;",
        "  BEGIN",
        `    OPEN v_cur FOR SELECT * FROM ${tableName} OFFSET p_offset ROWS FETCH NEXT p_limit ROWS ONLY;`,
        "    RETURN v_cur;",
        "  END F_LIST;",
      );
    }
    out.push(`END ${pkg};`, "/", "");
  });
  return out.join("\n");
}

export function exportSchema(schema: Schema) {
  return `${generateDDL(schema)}\n\n${generatePLSQL(schema)}`;
}
