#!/usr/bin/env bash
# Install (or remove) the boot hook that runs scripts/boot-drawsql.sh, using
# whatever init system the host actually has:
#
#   macOS            launchd user agent  ~/Library/LaunchAgents/com.drawsql.boot.plist
#   Linux (root)     systemd system unit /etc/systemd/system/drawsql.service
#   Linux (user)     systemd user unit   ~/.config/systemd/user/drawsql.service
#
# Usage:  ./scripts/install-boot.sh [--uninstall]
# The unit is generated from this checkout's path, so it works from any clone.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOOT="$REPO/scripts/boot-drawsql.sh"
LABEL="com.drawsql.boot"
# Compose derives the project name from the directory unless told otherwise.
PROJECT="${COMPOSE_PROJECT_NAME:-$(basename "$REPO" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_-')}"
UNINSTALL=false
[ "${1:-}" = "--uninstall" ] && UNINSTALL=true

chmod +x "$BOOT"

# macOS denies launchd agents access to ~/Documents, ~/Desktop and ~/Downloads
# (TCC) unless the user grants Full Disk Access by hand, so the agent cannot be
# pointed straight at a checkout living in one of those. The shim below lives in
# Application Support, which is always readable: it starts Docker, then runs the
# repo script if it can reach it and otherwise starts the project's existing
# containers by label — which needs no filesystem access at all.
write_shim() {
  local shim="$1"
  mkdir -p "$(dirname "$shim")"
  cat > "$shim" <<SHIM
#!/bin/bash
# Generated by scripts/install-boot.sh — edit that, not this.
set -uo pipefail
export PATH="\$PATH:/usr/local/bin:/opt/homebrew/bin:/Applications/Docker.app/Contents/Resources/bin"
LOG="\$HOME/Library/Logs/drawsql-boot.log"
log() { echo "\$(date '+%Y-%m-%d %H:%M:%S') drawsql-boot: \$*" >> "\$LOG"; }

docker info >/dev/null 2>&1 || open -ga Docker || { log "could not launch Docker Desktop"; exit 1; }
for _ in \$(seq 1 90); do docker info >/dev/null 2>&1 && break; sleep 2; done
docker info >/dev/null 2>&1 || { log "the docker daemon never came up"; exit 1; }

# \`test -r\` is not enough: under TCC access(2) succeeds where open(2) is denied,
# so prove readability by actually reading a byte.
if head -c1 "$BOOT" >/dev/null 2>&1; then exec /bin/bash "$BOOT"; fi

log "cannot read $BOOT (macOS TCC); starting containers by project label instead"
ids=\$(docker ps -aq --filter "label=com.docker.compose.project=$PROJECT")
if [ -n "\$ids" ]; then docker start \$ids >> "\$LOG" 2>&1 && log "started existing $PROJECT containers"
else log "no $PROJECT containers exist yet — run 'docker compose up -d' once, or grant /bin/bash Full Disk Access"; exit 1; fi
SHIM
  chmod +x "$shim"
}

install_launchd() {
  local plist="$HOME/Library/LaunchAgents/$LABEL.plist"
  local log="$HOME/Library/Logs/drawsql-boot.log"
  local shim="$HOME/Library/Application Support/drawsql/boot.sh"
  # `bootout` on a not-loaded agent exits non-zero; that is fine either way.
  launchctl bootout "gui/$(id -u)" "$plist" 2>/dev/null || true
  if $UNINSTALL; then rm -f "$plist" "$shim"; echo "Removed $plist"; return; fi
  mkdir -p "$(dirname "$plist")" "$(dirname "$log")"
  write_shim "$shim"
  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>$LABEL</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/bash</string>
		<string>$shim</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardOutPath</key>
	<string>$log</string>
	<key>StandardErrorPath</key>
	<string>$log</string>
</dict>
</plist>
PLIST
  launchctl bootstrap "gui/$(id -u)" "$plist"
  echo "Installed $plist — runs at every login. Log: $log"
}

write_unit() {
  cat > "$1" <<UNIT
[Unit]
Description=drawsql docker compose stack
Wants=network-online.target
After=network-online.target docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$REPO
ExecStart=/bin/bash $BOOT
ExecStop=/usr/bin/env docker compose down
TimeoutStartSec=600

[Install]
WantedBy=$2
UNIT
}

install_systemd() {
  local scope unit target
  if [ "$(id -u)" = 0 ]; then scope=(--system); unit=/etc/systemd/system/drawsql.service; target=multi-user.target
  else scope=(--user); unit="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/drawsql.service"; target=default.target; fi

  if $UNINSTALL; then
    systemctl "${scope[@]}" disable --now drawsql.service 2>/dev/null || true
    rm -f "$unit"; systemctl "${scope[@]}" daemon-reload; echo "Removed $unit"; return
  fi

  mkdir -p "$(dirname "$unit")"
  write_unit "$unit" "$target"
  systemctl "${scope[@]}" daemon-reload
  systemctl "${scope[@]}" enable --now drawsql.service
  # Without lingering, a user unit is torn down the moment the session ends and
  # never starts at boot — which is the whole point here.
  [ "$(id -u)" != 0 ] && command -v loginctl >/dev/null && loginctl enable-linger "$USER" 2>/dev/null || true
  echo "Installed $unit — starts at boot. Follow with: systemctl ${scope[*]} status drawsql"
}

case "$(uname -s)" in
  Darwin) install_launchd ;;
  Linux)
    if command -v systemctl >/dev/null 2>&1; then install_systemd
    else
      echo "No systemd here. Two options that need nothing installed:" >&2
      echo "  1. \`restart: unless-stopped\` in docker-compose.yml already restarts the stack whenever the docker daemon starts." >&2
      echo "  2. Add to crontab:  @reboot $BOOT" >&2
      exit 1
    fi ;;
  MINGW*|MSYS*|CYGWIN*)
    echo "Windows: run the PowerShell installer instead (Task Scheduler, not launchd/systemd):" >&2
    echo "  powershell -ExecutionPolicy Bypass -File scripts\\install-boot.ps1" >&2
    exit 1 ;;
  *) echo "Unsupported platform $(uname -s); run $BOOT from your own init system." >&2; exit 1 ;;
esac
